// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-sims.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/lib/inventory.ts
var NETWORK_PREFIXES = {
  MobiFone: ["089", "090", "093", "070", "076", "077", "078", "079"],
  Viettel: ["086", "096", "097", "098", "032", "033", "034", "035", "036", "037", "038", "039"],
  Vinaphone: ["088", "091", "094", "081", "082", "083", "084", "085"],
  Vietnamobile: ["092", "056", "058"],
  Gmobile: ["099", "059"]
};
function detectNetwork(digits) {
  const p = digits.slice(0, 3);
  for (const [name, prefixes] of Object.entries(NETWORK_PREFIXES)) {
    if (prefixes.includes(p)) return name;
  }
  return "Kh\xE1c";
}
function detectTags(digits) {
  const tags = [];
  const last2 = digits.slice(-2);
  const last3 = digits.slice(-3);
  const last4 = digits.slice(-4);
  const last6 = digits.slice(-6);
  if (/(\d)\1{5}$/.test(digits)) tags.push("L\u1EE5c qu\xFD");
  else if (/(\d)\1{4}$/.test(digits)) tags.push("Ng\u0169 qu\xFD");
  else if (/(\d)\1{3}$/.test(digits)) tags.push("T\u1EE9 qu\xFD");
  else if (/(\d)\1{2}$/.test(digits)) tags.push("Tam hoa");
  if (["68", "86"].includes(last2)) tags.push("L\u1ED9c ph\xE1t");
  if (["39", "79", "38", "78"].includes(last2)) tags.push("Th\u1EA7n t\xE0i");
  if (last4[0] === last4[2] && last4[1] === last4[3] && last4[0] !== last4[1]) tags.push("L\u1EB7p k\xE9p");
  if (/^(\d)(\d)\1\2\1\2$/.test(last6)) tags.push("Taxi");
  if (["012", "123", "234", "345", "456", "567", "678", "789"].includes(last3)) tags.push("Ti\u1EBFn");
  if (digits.slice(-5) === [...digits.slice(-5)].reverse().join("")) tags.push("G\xE1nh \u0111\u1EA3o");
  return tags;
}
function formatVnd(value) {
  return new Intl.NumberFormat("vi-VN").format(value) + " \u0111";
}
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else inQuotes = false;
      } else field += c;
      continue;
    }
    if (c === '"') {
      inQuotes = true;
      continue;
    }
    if (c === ",") {
      row.push(field);
      field = "";
      continue;
    }
    if (c === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
      continue;
    }
    if (c === "\r") continue;
    field += c;
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}
function toNumber(value) {
  const cleaned = String(value || "").replace(/[^\d]/g, "");
  return cleaned ? Number(cleaned) : 0;
}
var HIDDEN_STATUSES = ["sold", "reserved", "\u1EA9n", "an"];
var cache = null;
var CACHE_MS = 6e4;
async function fetchInventory() {
  if (cache && Date.now() - cache.at < CACHE_MS) return cache.rows;
  const baseUrl = process.env.SUPABASE_URL;
  const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!baseUrl) throw new Error("Inventory source is not configured.");
  const response = await fetch(`${baseUrl}/functions/v1/fetch-sim-data`, {
    method: "POST",
    headers: anonKey ? { apikey: anonKey, Authorization: `Bearer ${anonKey}` } : {}
  });
  if (!response.ok) throw new Error(`Inventory request failed (HTTP ${response.status})`);
  const csv = await response.text();
  const table = parseCsv(csv);
  if (table.length < 2) return [];
  const header = table[0].map((h) => h.trim().toUpperCase());
  const idx = (...names) => {
    for (const n of names) {
      const i = header.indexOf(n);
      if (i !== -1) return i;
    }
    return -1;
  };
  const iId = idx("SIMID");
  const iRaw = idx("RAW", "DISPLAY");
  const iDisplay = idx("DISPLAY", "RAW");
  const iOriginal = idx("ORIGINAL_PRICE", "PRICE");
  const iFinal = idx("FINAL_PRICE");
  const iStatus = idx("TRANG_THAI", "TR\u1EA0NG TH\xC1I", "TRANG THAI");
  const rows = [];
  for (let r = 1; r < table.length; r++) {
    const cells = table[r];
    if (!cells || cells.length === 0) continue;
    const status = (iStatus >= 0 ? cells[iStatus] ?? "" : "").trim().toLowerCase();
    if (HIDDEN_STATUSES.includes(status)) continue;
    const rawValue = iRaw >= 0 ? cells[iRaw] ?? "" : "";
    let digits = rawValue.replace(/\D/g, "");
    if (digits.length < 9) continue;
    if (digits.length === 9) digits = `0${digits}`;
    const originalPrice = iOriginal >= 0 ? toNumber(cells[iOriginal] ?? "") : 0;
    const finalPrice = iFinal >= 0 ? toNumber(cells[iFinal] ?? "") : 0;
    const price = finalPrice > 0 ? finalPrice : originalPrice;
    if (price <= 0) continue;
    rows.push({
      id: (iId >= 0 ? cells[iId] ?? "" : "").trim() || `sim-${r}`,
      digits,
      display: (iDisplay >= 0 ? cells[iDisplay] ?? "" : "").trim() || digits,
      price,
      originalPrice: originalPrice > 0 ? originalPrice : price,
      network: detectNetwork(digits),
      tags: detectTags(digits)
    });
  }
  cache = { rows, at: Date.now() };
  return rows;
}
function matchesPattern(digits, pattern) {
  const clean = pattern.replace(/[^\d*]/g, "");
  if (!clean) return true;
  if (!clean.includes("*")) return digits.endsWith(clean);
  const regex = new RegExp(`^${clean.replace(/\*/g, "\\d*")}$`);
  return regex.test(digits) || regex.test(digits.slice(1));
}

// src/lib/mcp/tools/search-sims.ts
var search_sims_default = defineTool({
  name: "search_sims",
  title: "T\xECm SIM s\u1ED1 \u0111\u1EB9p",
  description: 'Search the public SIM inventory. Supports a digit pattern (use * as a wildcard, e.g. "*6868" or "09*8888"), network filter, price range and tag filter.',
  inputSchema: {
    pattern: z.string().describe("Digits and * only. A plain digit string matches the SIM suffix.").optional(),
    network: z.enum(["MobiFone", "Viettel", "Vinaphone", "Vietnamobile", "Gmobile"]).describe("Restrict results to one mobile network.").optional(),
    min_price: z.number().describe("Minimum price in VND.").optional(),
    max_price: z.number().describe("Maximum price in VND.").optional(),
    tag: z.string().describe('Tag such as "T\u1EE9 qu\xFD", "Tam hoa", "L\u1ED9c ph\xE1t", "Th\u1EA7n t\xE0i", "Taxi", "Ti\u1EBFn".').optional(),
    limit: z.number().describe("Max results to return (1-50, default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pattern, network, min_price, max_price, tag, limit }) => {
    try {
      const all = await fetchInventory();
      const max = Math.min(Math.max(limit ?? 20, 1), 50);
      const matched = all.filter((sim) => {
        if (pattern && !matchesPattern(sim.digits, pattern)) return false;
        if (network && sim.network !== network) return false;
        if (typeof min_price === "number" && sim.price < min_price) return false;
        if (typeof max_price === "number" && sim.price > max_price) return false;
        if (tag && !sim.tags.some((t) => t.toLowerCase() === tag.toLowerCase())) return false;
        return true;
      });
      const results = matched.slice(0, max).map((sim) => ({
        id: sim.id,
        number: sim.display,
        digits: sim.digits,
        price: sim.price,
        price_text: formatVnd(sim.price),
        network: sim.network,
        tags: sim.tags,
        url: `https://www.chonsomobifone.com/mua-ngay/${encodeURIComponent(sim.id)}`
      }));
      const text = results.length ? results.map((r) => `${r.number} \u2014 ${r.price_text} \u2014 ${r.network}${r.tags.length ? ` (${r.tags.join(", ")})` : ""}`).join("\n") : "Kh\xF4ng t\xECm th\u1EA5y SIM ph\xF9 h\u1EE3p.";
      return {
        content: [
          { type: "text", text: `${results.length}/${matched.length} k\u1EBFt qu\u1EA3:
${text}` }
        ],
        structuredContent: { total_matches: matched.length, returned: results.length, results }
      };
    } catch (error) {
      return {
        content: [{ type: "text", text: `Kh\xF4ng t\u1EA3i \u0111\u01B0\u1EE3c kho SIM: ${error.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get-sim-details.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_sim_details_default = defineTool2({
  name: "get_sim_details",
  title: "Chi ti\u1EBFt SIM",
  description: "Look up one SIM number in the public inventory and return its price, network, tags, feng-shui digit sum and order link.",
  inputSchema: {
    number: z2.string().describe("The SIM number, digits only or formatted (e.g. 0938.868.868).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ number }) => {
    let digits = number.replace(/\D/g, "");
    if (digits.length === 9) digits = `0${digits}`;
    if (digits.length < 10) {
      return { content: [{ type: "text", text: "S\u1ED1 SIM kh\xF4ng h\u1EE3p l\u1EC7." }], isError: true };
    }
    const sumDigits = [...digits].reduce((acc, d) => acc + Number(d), 0);
    try {
      const all = await fetchInventory();
      const sim = all.find((s) => s.digits === digits);
      if (!sim) {
        return {
          content: [
            {
              type: "text",
              text: `SIM ${digits} hi\u1EC7n kh\xF4ng c\xF3 trong kho. M\u1EA1ng: ${detectNetwork(digits)}. T\u1ED5ng n\xFAt: ${sumDigits}. Li\xEAn h\u1EC7 hotline 0938.868.868 \u0111\u1EC3 t\xECm s\u1ED1 t\u01B0\u01A1ng t\u1EF1.`
            }
          ],
          structuredContent: {
            available: false,
            digits,
            network: detectNetwork(digits),
            tags: detectTags(digits),
            sum_digits: sumDigits
          }
        };
      }
      const detail = {
        available: true,
        id: sim.id,
        number: sim.display,
        digits: sim.digits,
        price: sim.price,
        price_text: formatVnd(sim.price),
        original_price: sim.originalPrice,
        discounted: sim.price < sim.originalPrice,
        network: sim.network,
        tags: sim.tags,
        sum_digits: sumDigits,
        url: `https://www.chonsomobifone.com/mua-ngay/${encodeURIComponent(sim.id)}`
      };
      return {
        content: [
          {
            type: "text",
            text: `${detail.number} \u2014 ${detail.price_text} \u2014 ${detail.network}${detail.tags.length ? ` (${detail.tags.join(", ")})` : ""}. T\u1ED5ng n\xFAt: ${sumDigits}. \u0110\u1EB7t mua: ${detail.url}`
          }
        ],
        structuredContent: detail
      };
    } catch (error) {
      return {
        content: [{ type: "text", text: `Kh\xF4ng t\u1EA3i \u0111\u01B0\u1EE3c kho SIM: ${error.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get-shop-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_shop_info_default = defineTool3({
  name: "get_shop_info",
  title: "Th\xF4ng tin c\u1EEDa h\xE0ng",
  description: "Return CHONSOMOBIFONE contact channels, store address, payment/delivery info and a snapshot of the current public inventory (count, price range, networks).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const shop = {
      name: "CHONSOMOBIFONE",
      website: "https://www.chonsomobifone.com",
      hotline: "0938.868.868",
      zalo: "https://zalo.me/0933356666",
      address: "43A \u0110\u01B0\u1EDDng s\u1ED1 9, Ph\u01B0\u1EDDng T\xE2n H\u01B0ng, TP.HCM",
      payment: {
        bank: "TECHCOMBANK",
        account_name: "NGUY\u1EC4N HO\xC0I TH\u01AF\u01A0NG",
        account_number: "5286797979",
        page: "https://www.chonsomobifone.com/thanh-toan"
      },
      delivery: "Giao sim mi\u1EC5n ph\xED to\xE0n qu\u1ED1c, ki\u1EC3m tra tr\u01B0\u1EDBc khi nh\u1EADn, cam k\u1EBFt ch\xEDnh ch\u1EE7."
    };
    let inventory = { available: false };
    try {
      const all = await fetchInventory();
      if (all.length) {
        const prices = all.map((s) => s.price);
        const networks = {};
        for (const sim of all) networks[sim.network] = (networks[sim.network] ?? 0) + 1;
        inventory = {
          available: true,
          total_sims: all.length,
          min_price: Math.min(...prices),
          max_price: Math.max(...prices),
          min_price_text: formatVnd(Math.min(...prices)),
          max_price_text: formatVnd(Math.max(...prices)),
          networks
        };
      }
    } catch {
      inventory = { available: false, note: "Kh\xF4ng t\u1EA3i \u0111\u01B0\u1EE3c kho SIM l\xFAc n\xE0y." };
    }
    return {
      content: [
        {
          type: "text",
          text: `${shop.name} \u2014 Hotline ${shop.hotline} \u2014 Zalo ${shop.zalo}
\u0110\u1ECBa ch\u1EC9: ${shop.address}
Thanh to\xE1n: ${shop.payment.bank} ${shop.payment.account_number} (${shop.payment.account_name})
${shop.delivery}`
        }
      ],
      structuredContent: { shop, inventory }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "chonsomobifone",
  title: "CHONSOMOBIFONE",
  version: "0.1.0",
  instructions: "Tools for CHONSOMOBIFONE, a Vietnamese beautiful-SIM shop. Use `search_sims` to find SIM numbers by digit pattern (* wildcard), network, price range or tag; `get_sim_details` to check one number; `get_shop_info` for contact, payment and inventory overview. All data is public.",
  tools: [search_sims_default, get_sim_details_default, get_shop_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
