// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
// Env vars with fallbacks live in ./config so a deploy with an unset
// environment doesn't build `undefined` into the client. See that file.
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});